[package]
name = "hzlang_parser"
version = "3.0.0"
edition = "2021"
license = "MIT"
description = "A parser for the \"hz\" programming language"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parco = "3.0.1"
